kind: pipeline
name: default

steps:
  # Run tests against React client app (with Jest)
  - name: client_test
    image: node:11.6.0-alpine
    commands:
      # Install dependencies (which will be cached)
      - node -v
      - npm install
      
  - name: wait_test
    image: golang
    commands:
      # Install dependencies (which will be cached)
      - pwd
      - sleep 3
      - go version
